name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "csamuel/dotfiles"
          rolling: true
          visibility: "public"
          include-output-paths: true
