# SOPS configuration file
# This file defines encryption keys and rules for secrets management
# Documentation: https://github.com/Mic92/sops-nix

# Define your encryption keys here
keys:
  # Example: Add your age public keys here
  # - &admin-key age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # - &user-key age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

# Define which keys can decrypt which files
creation_rules:
  # Default rule for all secrets
  - path_regex: secrets\.yaml$
    # age: *admin-key
    # Uncomment and add your age public key above

  # Example: Host-specific secrets
  # - path_regex: secrets/higgins\.yaml$
  #   age: *user-key

  # Example: Shared secrets
  # - path_regex: secrets/shared\.yaml$
  #   age:
  #     - *admin-key
  #     - *user-key
